### ISSUE TITLE
Feature request: logging error message if IMAP copy operation fails

### ISSUE THREAD

**Issue by RealRalph** [reneeb/otrs-IMAPMove#1]
If the IMAP copy operation fails, control immediately loops to processing the next message. It would be helpful to record the error message provided by errstr() in the OTRS log. The attempt to copy into a non-existing folder would, for example, be easier to spot.

**Comment by reneeb** [comment]
Fixed in 3d54b01

**Comment by RealRalph** [comment]
The fix works. Thank you.
